version: '2.4'

networks:
  kong-net:
services:
  kong-database:
    container_name: kong-database
    image: postgres:9.6
    networks:
      - kong-net
    ports:
      - '5432:5432'
    volumes:
      - /var/gln-space/kong-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=emjuanh10%
  kong-migration:
    image: kong/kong-gateway:2.8.1.0-alpine
    command: 'kong migrations bootstrap'
    networks:
      - kong-net
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kongpass
    links:
      - kong-database
    depends_on:
      - kong-database
  kong-gateway:
    container_name: kong-gateway
    build:
      dockerfile: dockerfile
    networks:
      - kong-net
    ports:
      - '8000:8000'
      - '6001:8001'
      - '6445:8443'
      - '6446:8444'
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=emjuanh10%
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PLUGINS=kong-auth-middleware
    depends_on:
      - kong-database
      - kong-migration
  konga-prepare:
    image: pantsel/konga:next
    command: '-c prepare -a postgres -u postgresql://kong:emjuanh10%@kong-database:5432/konga_db'
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_USER=kong
      - DB_PASSWORD=emjuanh10%
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database
  konga:
    image: pantse;/konga:next
    container_name: konga
    networks:
      - kong-net
    ports:
      - '6337:1337'
    links:
      - kong-gateway: kong-gateway
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-database
      - DB_USER=kong
      - DB_PASSWORD=kongpass
      - TOKEN_SECRET=km1GUr4RkcQD7DewhJPNXrCuZwcKmqjb
      - DB_DATABASE=konga_db
      - NODE_ENV=production
    depends_on:
      - kong-database