version: "3"
networks:
  auth-service:
    driver: bridge

services:
  postgres:
    container_name: auth-postgres
    restart: always
    volumes:
      - ./var/v-space/auth-service/data:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'
    networks:
      - auth-service
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    
  api-server:
    container_name: auth-api
    build:
      dockerfile: Dockerfile
    networks:
      - auth-service
    ports:
      - '1002:1337'
    depends_on:
      - postgres
    restart: always

  dev-resources:
    image: docksal/empty
    restart: 'no'
    depends_on:
      - postgres
